apiVersion: v1
kind: PersistentVolume
metadata:
  name: retro-aim
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume1/Kubernetes/retro-aim/data     # The path to your config
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
