apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retro-aim-pvc
spec:
  volumeName: retro-aim
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
